api_platform:
    use_symfony_listeners: true
    title: Blog API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
