lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'               # your passphrase
    token_ttl: 3600

    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: password