name: CI

on: [push, pull_request]

jobs:
    phpcs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: mbstring, intl, pdo_sqlite

            - name: Generate APP_SECRET
              id: generate_app_secret
              run: echo "APP_SECRET=$(openssl rand -hex 16)" >> $GITHUB_ENV

            - name: Create .env.local file
              run: |
                  echo 'APP_ENV=prod' >> .env.local
                  echo "APP_SECRET=${{ env.APP_SECRET }}" >> .env.local
                  echo 'DATABASE_URL="sqlite:///%kernel.project_dir%/var/data_prod.db"' >> .env.local

            - name: Create SQLite databases
              run: |
                  mkdir -p var
                  touch var/data_prod.db

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

            - name: Run database migrations for production
              run: php bin/console doctrine:migrations:migrate --env=prod --no-interaction

            - name: Clear Symfony cache
              run: php bin/console cache:clear --env=prod

            - name: Run PHP CodeSniffer
              run: |
                vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard
                vendor/bin/phpcs
