name: CI

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: mbstring, intl, pdo_sqlite

            - name: Generate APP_SECRET
              id: generate_app_secret
              run: echo "APP_SECRET=$(openssl rand -hex 16)" >> $GITHUB_ENV

            - name: Create .env.local file
              run: |
                  echo 'APP_ENV=prod' >> .env.local
                  echo "APP_SECRET=${{ env.APP_SECRET }}" >> .env.local
                  echo 'DATABASE_URL="sqlite:///%kernel.project_dir%/var/data/ci_test_database.sqlite"' >> .env.local

            - name: Create .env.test.local file
              run: |
                  echo 'DATABASE_URL="sqlite:///%kernel.project_dir%/var/data/ci_test_database_test.sqlite"' >> .env.test.local

            - name: Create SQLite databases
              run: |
                  mkdir -p var/data
                  touch var/data/ci_test_database.sqlite
                  touch var/data/ci_test_database_test.sqlite

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run database migrations for production
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/ci_test_database.sqlite
              run: php bin/console doctrine:migrations:migrate --env=prod --no-interaction

            - name: Run database migrations for test
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/ci_test_database_test.sqlite
              run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

            - name: Clear cache for test
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/ci_test_database_test.sqlite
              run: php bin/console cache:clear --env=test
            
            - name: Run tests Entity
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/ci_test_database_test.sqlite
              run: ./bin/phpunit tests/Entity

            - name: Run tests Form
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/ci_test_database_test.sqlite
              run: ./bin/phpunit tests/Form

            - name: Run tests Controller
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/ci_test_database_test.sqlite
              run: ./bin/phpunit tests/Controller
